import type { SocarengueSeedData } from "@/types/content";

const stamp = "2026-05-13T09:00:00.000Z";

export const issueOnePreviewPageSpecs = [
  {
    artifactId: "artifact_issue_01_cover",
    mediaId: "media_issue_01_cover",
    label: "Issue One Preview Cover",
    classification: "Preview cover",
    mediaType: "cover",
    source: "/artifacts/issue-01/publish/01-cover-final.png",
  },
  {
    artifactId: "artifact_issue_01_page_01",
    mediaId: "media_issue_01_page_01",
    label: "Issue One Preview Page 1",
    classification: "Preview comic page",
    mediaType: "panel",
    source: "/artifacts/issue-01/publish/02-opening-spread.png",
  },
  {
    artifactId: "artifact_issue_01_page_02",
    mediaId: "media_issue_01_page_02",
    label: "Issue One Preview Page 2",
    classification: "Preview comic page",
    mediaType: "panel",
    source: "/artifacts/issue-01/publish/03-rival-reveal.png",
  },
  {
    artifactId: "artifact_issue_01_page_03",
    mediaId: "media_issue_01_page_03",
    label: "Issue One Preview Page 3",
    classification: "Preview comic page",
    mediaType: "panel",
    source: "/artifacts/issue-01/publish/04-countdown-boom.png",
  },
  {
    artifactId: "artifact_issue_01_page_04",
    mediaId: "media_issue_01_page_04",
    label: "Issue One Preview Page 4",
    classification: "Preview comic page",
    mediaType: "panel",
    source: "/artifacts/issue-01/publish/05-battle-escalation.png",
  },
  {
    artifactId: "artifact_issue_01_page_05",
    mediaId: "media_issue_01_page_05",
    label: "Blackout Sequence",
    classification: "Blackout sequence",
    mediaType: "panel",
    source: "/artifacts/issue-01/publish/06-blackout.png",
  },
  {
    artifactId: "artifact_issue_01_page_06",
    mediaId: "media_issue_01_page_06",
    label: "Aftermath Preview",
    classification: "Preview comic page",
    mediaType: "panel",
    source: "/artifacts/issue-01/publish/07-aftermath.png",
  },
  {
    artifactId: "artifact_issue_01_final_signal",
    mediaId: "media_issue_01_final_signal",
    label: "Final Signal",
    classification: "Final image",
    mediaType: "panel",
    source: "/artifacts/issue-01/publish/08-final-signal.png",
  },
] as const;

export const developmentVaultSpecs = [
  {
    artifactId: "artifact_vault_early_comic_concept",
    mediaId: "media_vault_early_comic_concept",
    title: "Early Comic Concept",
    classification: "Early Concept",
    source: "/artifacts/issue-01/masters/concepts/early-style-tests/early-socarengue-comic-concept-v1.png",
    mediaType: "concept",
  },
  {
    artifactId: "artifact_vault_ovi_origin_grid",
    mediaId: "media_vault_ovi_origin_grid",
    title: "Ovi Origin Grid",
    classification: "Worldbuilding Study",
    source: "/artifacts/issue-01/masters/concepts/ovi-origin-awakening-concept-grid-v1.png",
    mediaType: "concept",
  },
  {
    artifactId: "artifact_vault_son_of_rhythm_guide",
    mediaId: "media_vault_son_of_rhythm_guide",
    title: "Son of Rhythm Guide",
    classification: "Worldbuilding Study",
    source: "/artifacts/issue-01/masters/concepts/ovi-son-of-rhythm-visual-guide-v1.png",
    mediaType: "concept",
  },
  {
    artifactId: "artifact_vault_textless_cover",
    mediaId: "media_vault_textless_cover",
    title: "Textless Cover Study",
    classification: "Visual Study",
    source: "/artifacts/issue-01/masters/covers/socarengue-issue-01-the-sticks-return-cover-textless.png",
    mediaType: "cover",
  },
  {
    artifactId: "artifact_vault_alt_cover",
    mediaId: "media_vault_alt_cover",
    title: "Alternate Cover Study",
    classification: "Visual Study",
    source: "/artifacts/issue-01/masters/covers/socarengue-issue-01-the-sticks-return-cover-alt-a.png",
    mediaType: "cover",
  },
  {
    artifactId: "artifact_vault_storyboard_sheet",
    mediaId: "media_vault_storyboard_sheet",
    title: "Opening Movement Storyboard Sheet",
    classification: "Storyboard Sheet",
    source: "/artifacts/issue-01/masters/layouts/socarengue-issue-01-layout-storyboard-sheet.png.PNG",
    mediaType: "storyboard",
  },
  {
    artifactId: "artifact_vault_drum_battle_layout",
    mediaId: "media_vault_drum_battle_layout",
    title: "Drum Battle Layout Study",
    classification: "Storyboard Sheet",
    source: "/artifacts/issue-01/masters/layouts/issue-01-page-002-drum-battle-opening-v1.png",
    mediaType: "storyboard",
  },
  {
    artifactId: "artifact_vault_awakening_panel",
    mediaId: "media_vault_awakening_panel",
    title: "Glowing Sticks Awakening Study",
    classification: "Alternate Page",
    source: "/artifacts/issue-01/masters/concepts/early-style-tests/glowing-sticks-awakening-panel-v1.png",
    mediaType: "panel",
  },
  {
    artifactId: "artifact_vault_drumoff_opening",
    mediaId: "media_vault_drumoff_opening",
    title: "Drumoff Opening Study",
    classification: "Alternate Page",
    source: "/artifacts/issue-01/masters/concepts/early-style-tests/socarengue-issue-01-page-002-drumoff-opening.png",
    mediaType: "panel",
  },
  {
    artifactId: "artifact_vault_blackout_reveal",
    mediaId: "media_vault_blackout_reveal",
    title: "Blackout Reveal Study",
    classification: "Alternate Page",
    source: "/artifacts/issue-01/masters/pages/issue-01-page-003-004-blackout-reveal-v3.png",
    mediaType: "panel",
  },
  {
    artifactId: "artifact_vault_blackout_clean_layout",
    mediaId: "media_vault_blackout_clean_layout",
    title: "Blackout Clean Layout",
    classification: "Storyboard Sheet",
    source: "/artifacts/issue-01/masters/layouts/issue-01-page-003-004-blackout-clean-spread-v2.png",
    mediaType: "storyboard",
  },
] as const;

export const socarengueSeed: SocarengueSeedData = {
  project: {
    id: "project_socarengue",
    title: "Socarengue",
    slug: "socarengue",
    logline: "A serialized mythology of inherited rhythm, city memory, and songs that carry emotional power.",
    description:
      "Socarengue is a noir-neon archive of recovered transmissions: comic scenes, symbolic objects, music cues, and city fragments that reveal a living mythology.",
    tone: ["mythic", "musical", "atmospheric", "artifact-driven", "noir-neon"],
    status: "draft",
    createdAt: stamp,
    updatedAt: stamp,
  },
  issues: [
    {
      id: "issue_001",
      projectId: "project_socarengue",
      title: "Issue 01: The Street Remembers",
      slug: "the-street-remembers",
      issueNumber: 1,
      summary:
        "A buried rhythm leaks through a rain-soaked neighborhood after a recovered cassette begins matching the pulse of the city lights.",
      status: "draft",
      visibility: "review",
      coverMediaId: "media_cover_001",
      sceneIds: ["scene_rain_signal", "scene_cassette_room", "scene_underpass_chorus"],
      createdAt: stamp,
      updatedAt: stamp,
    },
  ],
  scenes: [
    {
      id: "scene_rain_signal",
      projectId: "project_socarengue",
      issueId: "issue_001",
      title: "Rain Signal",
      slug: "rain-signal",
      sequenceIndex: 1,
      summary: "Neon rain exposes a rhythm hidden inside a failing streetlight.",
      scriptText:
        "The block flickers in uneven time. Mara hears the light before she sees it: three pulses, a pause, then a low hum under the rain. At the curb, an old speaker coughs out a note that feels older than the city.",
      visualNotes:
        "Wet asphalt, sodium amber streetlight, cyan reflection, close crop on water rippling in rhythm.",
      emotionalBeat: "Recognition before understanding.",
      status: "draft",
      visibility: "public",
      characterIds: ["character_mara", "character_ovi"],
      artifactIds: ["artifact_broken_speaker"],
      mediaAssetIds: ["media_panel_rain", "media_frame_streetlight"],
      soundtrackCueIds: ["cue_rain_low_loop"],
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "scene_cassette_room",
      projectId: "project_socarengue",
      issueId: "issue_001",
      title: "The Cassette Room",
      slug: "the-cassette-room",
      sequenceIndex: 2,
      summary: "A cassette labeled in gold ink plays a chorus nobody admits remembering.",
      scriptText:
        "Inside the back room, the tape deck turns without being plugged in. The chorus is soft, almost ruined, but Lucien writes every word before the sound collapses into static.",
      visualNotes:
        "Dust, tape reels, warm gold ink, a table crowded with receipts, saints, and half-labeled recordings.",
      emotionalBeat: "The archive becomes intimate and dangerous.",
      status: "draft",
      visibility: "public",
      characterIds: ["character_mara", "character_lucien"],
      artifactIds: ["artifact_gold_cassette", "artifact_ledger_page"],
      mediaAssetIds: ["media_cassette", "media_room_still"],
      soundtrackCueIds: ["cue_gold_ink_chorus"],
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "scene_underpass_chorus",
      projectId: "project_socarengue",
      issueId: "issue_001",
      title: "Underpass Chorus",
      slug: "underpass-chorus",
      sequenceIndex: 3,
      summary: "A wall of old posters answers the cassette with a rhythm hidden in torn paper.",
      scriptText:
        "Under the tracks, every poster edge lifts in the same windless measure. Ovi taps the railing twice. The city answers with a harmony no instrument is playing.",
      visualNotes:
        "Layered posters, train-shadow bands, red paint, humid air, hands on cold metal.",
      emotionalBeat: "The city is not a setting. It is a witness.",
      status: "draft",
      visibility: "public",
      characterIds: ["character_ovi", "character_mara"],
      artifactIds: ["artifact_ovi_issue_artwork", "artifact_underpass_poster"],
      mediaAssetIds: ["media_ovi_issue_artwork", "media_underpass", "media_symbol_map"],
      soundtrackCueIds: ["cue_underpass_chorus", "cue_silent_afterimage"],
      createdAt: stamp,
      updatedAt: stamp,
    },
  ],
  characters: [
    {
      id: "character_mara",
      projectId: "project_socarengue",
      name: "Mara Vale",
      slug: "mara-vale",
      publicDescription:
        "A listener who notices rhythm in broken infrastructure: streetlights, train rails, rain gutters, and rooms that refuse silence.",
      privateNotes: "Mara's family line carried the first city rhythm after the blackout.",
      roleInStory: "Listener",
      resonanceProfile: "Memory, warning, inherited rhythm",
      portraitMediaId: "media_portrait_mara",
      status: "draft",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "character_ovi",
      projectId: "project_socarengue",
      name: "Ovi Reyes",
      slug: "ovi-reyes",
      publicDescription:
        "A musician whose live sets make hidden city patterns briefly audible to anyone standing close enough.",
      privateNotes: "Ovi can amplify resonance but cannot always separate his own grief from the signal.",
      roleInStory: "Amplifier",
      resonanceProfile: "Devotion, rupture, stage light",
      portraitMediaId: "media_portrait_ovi",
      status: "draft",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "character_lucien",
      projectId: "project_socarengue",
      name: "Lucien Mar",
      slug: "lucien-mar",
      publicDescription:
        "An archive keeper who catalogs recovered recordings, missing posters, and symbols that keep appearing in different decades.",
      privateNotes: "Lucien has already heard the final chorus, but misfiled it as a childhood memory.",
      roleInStory: "Keeper",
      resonanceProfile: "Archive, silence, contradiction",
      portraitMediaId: "media_portrait_lucien",
      status: "draft",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
  ],
  loreEntries: [
    {
      id: "lore_city_memory",
      projectId: "project_socarengue",
      title: "City Memory",
      slug: "city-memory",
      category: "myth",
      publicText:
        "The city holds emotional residue in places where music, grief, and repetition have pressed hard enough to leave a mark.",
      privateNotes: "City memory becomes strongest near old transit routes and closed venues.",
      canonicalStatus: "draft",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "lore_gold_ink",
      projectId: "project_socarengue",
      title: "Gold Ink",
      slug: "gold-ink",
      category: "symbol",
      publicText:
        "Gold ink marks recordings and notes believed to carry inherited rhythm rather than ordinary authorship.",
      privateNotes: "The ink is mixed with dust from a demolished dance hall.",
      canonicalStatus: "draft",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "lore_underpass_nine",
      projectId: "project_socarengue",
      title: "Underpass Nine",
      slug: "underpass-nine",
      category: "place",
      publicText:
        "A train underpass where torn posters, rainwater, and passing rails repeat phrases from songs never officially released.",
      privateNotes: "Underpass Nine is a threshold, not just a location.",
      canonicalStatus: "draft",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "lore_resonance",
      projectId: "project_socarengue",
      title: "Resonance",
      slug: "resonance",
      category: "phrase",
      publicText:
        "The name given to emotional frequency when it persists through sound, object, place, or person.",
      privateNotes: "Resonance is not evenly distributed; it gathers around unresolved inheritance.",
      canonicalStatus: "draft",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
  ],
  artifacts: [
    {
      id: "artifact_gold_cassette",
      projectId: "project_socarengue",
      title: "Cassette With Gold Ink",
      slug: "cassette-with-gold-ink",
      classification: "Recovered audio object",
      publicDescription:
        "A smoke-dark cassette labeled in metallic handwriting. The tape plays a chorus that seems to change depending on who hears it.",
      privateNotes: "This is the first public-facing object that should hint at inherited rhythm.",
      transcript: "Side A: three drum hits, rain static, a voice saying 'remember me in tempo.'",
      primaryMediaId: "media_cassette",
      linkedSceneIds: ["scene_cassette_room"],
      linkedLoreIds: ["lore_gold_ink", "lore_resonance"],
      linkedTrackIds: ["track_gold_ink_chorus"],
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "artifact_broken_speaker",
      projectId: "project_socarengue",
      title: "Broken Curb Speaker",
      slug: "broken-curb-speaker",
      classification: "Street relic",
      publicDescription:
        "A cracked portable speaker found near a flickering streetlight. It hums softly when rain hits the grille.",
      privateNotes: "Speaker is a receiver, not a source.",
      primaryMediaId: "media_frame_streetlight",
      linkedSceneIds: ["scene_rain_signal"],
      linkedLoreIds: ["lore_city_memory"],
      linkedTrackIds: ["track_rain_low_loop"],
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "artifact_ovi_issue_artwork",
      projectId: "project_socarengue",
      title: "Ovi Artwork",
      slug: "ovi-issue-artwork",
      classification: "Character artwork",
      publicDescription:
        "A first public image of Ovi at the edge of the story, caught between stage light, rhythm, and the city watching back.",
      privateNotes: "Use this as the first real local media-backed artifact and a bridge between Ovi, live resonance, and the underpass chorus.",
      transcript: "Margin inscription: 'the city answers in rhythm.'",
      primaryMediaId: "media_ovi_issue_artwork",
      linkedSceneIds: ["scene_underpass_chorus", "scene_rain_signal"],
      linkedLoreIds: ["lore_resonance", "lore_underpass_nine", "lore_city_memory"],
      linkedTrackIds: ["track_underpass_chorus", "track_rain_low_loop"],
      status: "draft",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "artifact_underpass_poster",
      projectId: "project_socarengue",
      title: "Torn Underpass Poster",
      slug: "torn-underpass-poster",
      classification: "Recovered visual fragment",
      publicDescription:
        "A layered poster fragment from Underpass Nine. Its torn edges form a waveform when held against train light.",
      privateNotes: "This poster hides the symbol map orientation.",
      primaryMediaId: "media_underpass",
      linkedSceneIds: ["scene_underpass_chorus"],
      linkedLoreIds: ["lore_underpass_nine"],
      linkedTrackIds: ["track_underpass_chorus"],
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "artifact_ledger_page",
      projectId: "project_socarengue",
      title: "Ledger Page 7",
      slug: "ledger-page-7",
      classification: "Archive document",
      publicDescription:
        "A hand-ruled ledger page listing dates, venues, missing reels, and a repeated note: 'Do not catalog the chorus alone.'",
      privateNotes: "This is Lucien's own handwriting from before he remembers writing it.",
      primaryMediaId: "media_ledger",
      linkedSceneIds: ["scene_cassette_room"],
      linkedLoreIds: ["lore_city_memory", "lore_resonance"],
      linkedTrackIds: [],
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
    ...issueOnePreviewPageSpecs.map((page) => ({
      id: page.artifactId,
      projectId: "project_socarengue",
      title: page.label,
      slug: page.label.toLowerCase().replaceAll(" ", "-"),
      classification: page.classification,
      publicDescription: "A curated image from the opening movement of Socarengue Issue One.",
      privateNotes: "Local Issue One page asset staged for public preview.",
      primaryMediaId: page.mediaId,
      linkedSceneIds: [],
      linkedLoreIds: [],
      linkedTrackIds: [],
      status: "draft" as const,
      visibility: "public" as const,
      createdAt: stamp,
      updatedAt: stamp,
    })),
    ...developmentVaultSpecs.map((item) => ({
      id: item.artifactId,
      projectId: "project_socarengue",
      title: item.title,
      slug: item.title.toLowerCase().replaceAll(" ", "-"),
      classification: item.classification,
      publicDescription: "Development material from the visual formation of Socarengue Issue One.",
      privateNotes: "Visible in the Development Vault as non-final visual process material.",
      primaryMediaId: item.mediaId,
      linkedSceneIds: [],
      linkedLoreIds: [],
      linkedTrackIds: [],
      status: "draft" as const,
      visibility: "public" as const,
      createdAt: stamp,
      updatedAt: stamp,
    })),
  ],
  mediaAssets: [
    {
      id: "media_ovi_issue_artwork",
      projectId: "project_socarengue",
      title: "Ovi Artwork",
      type: "cover",
      source: "/artifacts/issue-01/publish/01-cover-final.png",
      credit: "Socarengue Studio",
      rightsStatus: "local Issue One public preview artwork",
      altText:
        "Issue One preview cover artwork for The Sticks Return opening signal.",
      status: "draft",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
    ...issueOnePreviewPageSpecs.map((page) => ({
      id: page.mediaId,
      projectId: "project_socarengue",
      title: page.label,
      type: page.mediaType,
      source: page.source,
      credit: "Socarengue Studio",
      rightsStatus: "local Issue One public preview artwork",
      altText: `${page.label} from the Socarengue Issue One public preview.`,
      status: "draft" as const,
      visibility: "public" as const,
      createdAt: stamp,
      updatedAt: stamp,
    })),
    ...developmentVaultSpecs.map((item) => ({
      id: item.mediaId,
      projectId: "project_socarengue",
      title: item.title,
      type: item.mediaType,
      source: item.source,
      credit: "Socarengue Studio",
      rightsStatus: "local development vault artwork",
      altText: `${item.title}, categorized as ${item.classification}.`,
      status: "draft" as const,
      visibility: "public" as const,
      createdAt: stamp,
      updatedAt: stamp,
    })),
    {
      id: "media_cover_001",
      projectId: "project_socarengue",
      title: "Issue 01 Cover Study",
      type: "cover",
      source: "local-placeholder://cover-study",
      credit: "Socarengue Studio",
      rightsStatus: "internal concept metadata",
      altText: "A rain-dark street with cyan signal light and warm gold lettering.",
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "media_panel_rain",
      projectId: "project_socarengue",
      title: "Rain Ripple Panel",
      type: "panel",
      source: "local-placeholder://rain-ripple-panel",
      credit: "Socarengue Studio",
      rightsStatus: "internal concept metadata",
      altText: "Rain ripples reflecting amber and cyan light.",
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "media_frame_streetlight",
      projectId: "project_socarengue",
      title: "Streetlight Receiver Frame",
      type: "frame",
      source: "local-placeholder://streetlight-receiver-frame",
      credit: "Socarengue Studio",
      rightsStatus: "internal concept metadata",
      altText: "A cracked speaker under a flickering streetlight.",
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "media_cassette",
      projectId: "project_socarengue",
      title: "Gold Ink Cassette Reference",
      type: "image",
      source: "local-placeholder://gold-ink-cassette",
      credit: "Socarengue Studio",
      rightsStatus: "internal concept metadata",
      altText: "A cassette marked with gold ink on a dusty table.",
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "media_room_still",
      projectId: "project_socarengue",
      title: "Archive Back Room Still",
      type: "reference",
      source: "local-placeholder://archive-back-room",
      credit: "Socarengue Studio",
      rightsStatus: "internal concept metadata",
      altText: "A warm, dusty archive back room crowded with music relics.",
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "media_underpass",
      projectId: "project_socarengue",
      title: "Underpass Poster Wall",
      type: "image",
      source: "local-placeholder://underpass-poster-wall",
      credit: "Socarengue Studio",
      rightsStatus: "internal concept metadata",
      altText: "Layered torn posters beneath train tracks.",
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "media_symbol_map",
      projectId: "project_socarengue",
      title: "Waveform Map Sketch",
      type: "document",
      source: "local-placeholder://waveform-map-sketch",
      credit: "Socarengue Studio",
      rightsStatus: "internal concept metadata",
      altText: "A map marked with waveform lines and gold ink.",
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "media_ledger",
      projectId: "project_socarengue",
      title: "Ledger Page Scan",
      type: "document",
      source: "local-placeholder://ledger-page-7",
      credit: "Socarengue Studio",
      rightsStatus: "internal concept metadata",
      altText: "A hand-ruled ledger page with venue dates and notes.",
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "media_portrait_mara",
      projectId: "project_socarengue",
      title: "Mara Portrait Reference",
      type: "concept",
      source: "local-placeholder://mara-portrait",
      credit: "Socarengue Studio",
      rightsStatus: "internal concept metadata",
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "media_portrait_ovi",
      projectId: "project_socarengue",
      title: "Ovi Portrait Reference",
      type: "concept",
      source: "local-placeholder://ovi-portrait",
      credit: "Socarengue Studio",
      rightsStatus: "internal concept metadata",
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "media_portrait_lucien",
      projectId: "project_socarengue",
      title: "Lucien Portrait Reference",
      type: "concept",
      source: "local-placeholder://lucien-portrait",
      credit: "Socarengue Studio",
      rightsStatus: "internal concept metadata",
      status: "draft",
      visibility: "review",
      createdAt: stamp,
      updatedAt: stamp,
    },
  ],
  tracks: [
    {
      id: "track_rain_low_loop",
      projectId: "project_socarengue",
      title: "Rain Low Loop",
      slug: "rain-low-loop",
      artist: "Ovi Reyes",
      durationSeconds: 142,
      moodTags: ["rain", "recognition", "low pulse"],
      publicNotes: "A low ambient loop for the moment the streetlight begins answering the rain.",
      privateNotes: "Should feel like infrastructure remembering a song.",
      status: "draft",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "track_gold_ink_chorus",
      projectId: "project_socarengue",
      title: "Gold Ink Chorus",
      slug: "gold-ink-chorus",
      artist: "Socarengue Studio",
      durationSeconds: 198,
      moodTags: ["cassette", "inheritance", "fragile voice"],
      publicNotes: "A damaged chorus tied to the recovered cassette and the archive back room.",
      privateNotes: "Never present the full lyric in public this early.",
      status: "draft",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "track_underpass_chorus",
      projectId: "project_socarengue",
      title: "Underpass Chorus",
      slug: "underpass-chorus",
      artist: "Ovi Reyes",
      durationSeconds: 171,
      moodTags: ["train shadow", "paper", "city witness"],
      publicNotes: "A chorus built from rail hum, handclap delay, and a melody that seems to arrive from behind the wall.",
      privateNotes: "This track is the first proof that locations can answer.",
      status: "draft",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
  ],
  soundtrackCues: [
    {
      id: "cue_rain_low_loop",
      projectId: "project_socarengue",
      trackId: "track_rain_low_loop",
      targetType: "scene",
      targetId: "scene_rain_signal",
      cueLabel: "Low rain pulse",
      sequenceIndex: 1,
      instruction: "Begin softly as the streetlight starts to flicker. Silence is still a valid reading mode.",
      mood: "recognition before understanding",
      required: false,
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "cue_gold_ink_chorus",
      projectId: "project_socarengue",
      trackId: "track_gold_ink_chorus",
      targetType: "scene",
      targetId: "scene_cassette_room",
      cueLabel: "Damaged chorus",
      sequenceIndex: 2,
      instruction: "Let the chorus enter after the tape deck turns. Keep the lyric partial.",
      mood: "intimate danger",
      required: false,
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "cue_underpass_chorus",
      projectId: "project_socarengue",
      trackId: "track_underpass_chorus",
      targetType: "scene",
      targetId: "scene_underpass_chorus",
      cueLabel: "Rail harmony",
      sequenceIndex: 3,
      instruction: "Optional: start when Ovi taps the railing twice.",
      mood: "the city answers",
      required: false,
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "cue_silent_afterimage",
      projectId: "project_socarengue",
      trackId: "track_underpass_chorus",
      targetType: "artifact",
      targetId: "artifact_underpass_poster",
      cueLabel: "Afterimage silence",
      sequenceIndex: 4,
      instruction: "Stop before the artifact reveal. Let the poster feel louder than the track.",
      mood: "charged absence",
      required: false,
      createdAt: stamp,
      updatedAt: stamp,
    },
  ],
  releases: [
    {
      id: "release_issue_001",
      projectId: "project_socarengue",
      title: "Transmission 001: The Street Remembers",
      slug: "transmission-001-the-street-remembers",
      releaseType: "transmission",
      summary:
        "A first public-facing archive sequence connecting rain, cassette memory, and the underpass chorus.",
      status: "draft",
      visibility: "review",
      publishedAt: undefined,
      coverMediaId: "media_cover_001",
      createdAt: stamp,
      updatedAt: stamp,
    },
  ],
  releaseItems: [
    {
      id: "release_item_issue_001",
      releaseId: "release_issue_001",
      itemType: "issue",
      itemId: "issue_001",
      sequenceIndex: 1,
      presentationMode: "reader",
      publicNote: "Open the first issue as recovered sequence.",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "release_item_artifact_cassette",
      releaseId: "release_issue_001",
      itemType: "artifact",
      itemId: "artifact_gold_cassette",
      sequenceIndex: 2,
      presentationMode: "artifact",
      publicNote: "A cassette enters the archive before it enters the explanation.",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "release_item_artifact_ovi_artwork",
      releaseId: "release_issue_001",
      itemType: "artifact",
      itemId: "artifact_ovi_issue_artwork",
      sequenceIndex: 3,
      presentationMode: "artifact",
      publicNote: "Ovi's issue artwork enters as a visual resonance record.",
      createdAt: stamp,
      updatedAt: stamp,
    },
  ],
  relationships: [
    {
      id: "rel_ovi_artwork_scene",
      projectId: "project_socarengue",
      fromType: "artifact",
      fromId: "artifact_ovi_issue_artwork",
      toType: "scene",
      toId: "scene_underpass_chorus",
      relationshipType: "foreshadows",
      publicLabel: "Foreshadows the moment the city answers Ovi's rhythm.",
      privateNote: "The artwork should feel like it arrived before the event it depicts.",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "rel_ovi_artwork_track",
      projectId: "project_socarengue",
      fromType: "artifact",
      fromId: "artifact_ovi_issue_artwork",
      toType: "track",
      toId: "track_underpass_chorus",
      relationshipType: "soundtracks",
      publicLabel: "Carries the same rail harmony as the underpass chorus.",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "rel_scene_track_rain",
      projectId: "project_socarengue",
      fromType: "track",
      fromId: "track_rain_low_loop",
      toType: "scene",
      toId: "scene_rain_signal",
      relationshipType: "soundtracks",
      publicLabel: "Soundtracks the first rain signal.",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "rel_cassette_lore",
      projectId: "project_socarengue",
      fromType: "artifact",
      fromId: "artifact_gold_cassette",
      toType: "lore",
      toId: "lore_gold_ink",
      relationshipType: "reveals",
      publicLabel: "Reveals the gold ink marking system.",
      privateNote: "Public should not yet know who first used the ink.",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
    {
      id: "rel_underpass_city",
      projectId: "project_socarengue",
      fromType: "lore",
      fromId: "lore_underpass_nine",
      toType: "scene",
      toId: "scene_underpass_chorus",
      relationshipType: "belongs_to",
      publicLabel: "Anchors the underpass chorus.",
      visibility: "public",
      createdAt: stamp,
      updatedAt: stamp,
    },
  ],
  notes: [
    {
      id: "note_private_arc",
      projectId: "project_socarengue",
      targetType: "issue",
      targetId: "issue_001",
      body: "Private arc note: the chorus should point toward inherited rhythm without naming the origin yet.",
      status: "draft",
      visibility: "private",
      createdAt: stamp,
      updatedAt: stamp,
    },
  ],
};
